name: test
on:
  workflow_dispatch:
    inputs:
      name:
        description: '测试qemu'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # - uses: graalvm/setup-graalvm@v1.2.1
    #   with:
    #     java-version: '22'
    #     distribution: 'graalvm'
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    # - name: echo GRAALVM env
    #   run: |
    #     echo "GRAALVM_HOME: $GRAALVM_HOME"
    #     echo "JAVA_HOME: $JAVA_HOME"
    #     java --version
    #     native-image --version
    #     which java
    #     whereis java
    #     echo "JAVA_HOME=$JAVA_HOME" >> "$GITHUB_ENV"
    #     echo "GRAALVM_HOME=$GRAALVM_HOME" >> "$GITHUB_ENV"
    #     echo "目录是：$(pwd)，当前用户 `whoami`"
    # - uses: actions/checkout@v4.1.2
    - uses: uraimo/run-on-arch-action@v2.7.1
      name: Run aarch64
      id: build_aarch64
      with:
        arch: aarch64
        distro: ubuntu22.04
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        #宿主机runner运行的命令
        setup: |
           echo "==============runner setup"
           echo "setup 目录是：$(pwd)，当前用户 `whoami`"
           ls -alh
           # echo "GRAALVM_HOME: $GRAALVM_HOME"
           # echo "JAVA_HOME: $JAVA_HOME"
        # env: |
        #   GRAALVM_HOME: ${{ env.GRAALVM_HOME }}
        #   JAVA_HOME: ${{ env.JAVA_HOME }}
        install: |
          echo "==============aarch install"
          uname -a
          # apt-get update -qq -y
          # apt-get install -qq -y util-linux curl git build-essential libz-dev zlib1g-dev zip unzip
          apt-get update -qq -y
          apt-get install -qq -y util-linux curl
          # echo "install arch值：`arch`"
          # echo "install lscpu值：`lscpu`"
          curl -SOL https://download.oracle.com/graalvm/22/latest/graalvm-jdk-22_linux-aarch64_bin.tar.gz
          tar -zxf graalvm-jdk-22_linux-aarch64_bin.tar.gz
          cd graalvm-jdk-22+36.1
          echo " install 目录是：$(pwd)，当前用户 `whoami`"
          export JAVA_HOME=$(pwd)
          # export GRAALVM_HOME=$(pwd)
          echo "export JAVA_HOME=$(pwd)" >> /root/.bashrc
          echo "export GRAALVM_HOME=$(pwd)" >> /root/.bashrc
          # source ~/.bashrc
          echo "export PATH=$PATH:$JAVA_HOME/bin" >> /root/.bashrc
          # java --version
          # native-image --version
        #容器中运行的命令
        run: |
           env
           cat /root/.bashrc
           # uname -a
           # echo "==============aarch run"
           # echo "run arch值：`arch`"
           # echo "run lscpu值：`lscpu`"
           # echo "run path变量是：$PATH"
           # echo "run 目录是：$(pwd)，当前用户 `whoami`"
           # # ls -alh
           # echo "GRAALVM_HOME: $GRAALVM_HOME"
           # echo "JAVA_HOME: $JAVA_HOME"
           # which java
           # whereis java
           # java --version
           # native-image --version
        
